## import_data.m ###############################################################
import_data <- function(i, param_seq, scn) {
  
  # Assumed data set
  virus     <- param_seq$virus[i]
  period    <- param_seq$period[i]
  coprimary <- param_seq$coprimary[i]
  hh_size   <- param_seq$hh_size[i]
  type      <- param_seq$type[i]
  
  ## import_data.m ###############################################################
  
  # Load data generated by Lexie
  df_dat <- readRDS('../R/Data/covdat_deid.RDS')
  
  # Removing unused columns
  df_dat$cdc_num_cov_valid          <- NULL
  df_dat$cdc_firstspecdt            <- NULL
  df_dat$cdc_lastspecdt             <- NULL
  df_dat$index_symptom_or_test_date <- NULL
  df_dat$participant_type           <- NULL
  df_dat$cdc_agegrp                 <- NULL
  df_dat$cdc_cov_docordate_doses    <- NULL
  df_dat$cdc_cov_docordate_lastdt   <- NULL
  
  # Checking
  length(unique(df_dat$cdc_studyid)) # number of individuals
  length(unique(df_dat$cdc_hhid))    # number of households
  
  # Filter out those households with missing data of testing of the index case (!)
  df_dat <- df_dat %>%
    filter(!is.na(index_test_date))
  
  # One variant
  if(period == "All Omicron") df_dat <- df_dat %>% filter(cdc_period != "Delta: Sep-Dec 17, '21")
  if(period == "Delta")       df_dat <- df_dat %>% filter(cdc_period == "Delta: Sep-Dec 17, '21")
  if(period == "BA1")         df_dat <- df_dat %>% filter(cdc_period == "Omicron BA1/BA2: Dec 18, '21-Jun 17, '22")
  if(period == "BA4")         df_dat <- df_dat %>% filter(cdc_period == "Omicron BA4/5: Jun 18, '22-Jan 14, '23")
  if(period == "XBB")         df_dat <- df_dat %>% filter(cdc_period == "XBB etc: Jan 15-May 1, '23")
  # Removing column
  df_dat$cdc_period                 <- NULL
  
  # No co-primary cases
  if(coprimary == FALSE) df_dat <- df_dat %>% filter(cdc_cov_coprimary == 0)
  # Removing column
  df_dat$cdc_cov_coprimary          <- NULL
  
  # Checking
  length(unique(df_dat$cdc_studyid)) # number of individuals
  length(unique(df_dat$cdc_hhid))    # number of households
  
  ## Date of symptom onset #######################################################
  
  # Logical vectors
  df_dat$cdc_cov_pos       <- (df_dat$cdc_cov_pos       == 1) # tested positive
  df_dat$cdc_ever_symptoms <- (df_dat$cdc_ever_symptoms == 1) # symptomatic (not necessarily infected)
  
  df_dat$symp_all  <- ( df_dat$cdc_cov_pos) & ( df_dat$cdc_ever_symptoms) #  symptomatic infected
  df_dat$asymp_all <- ( df_dat$cdc_cov_pos) & (!df_dat$cdc_ever_symptoms) # asymptomatic infected
  df_dat$uninf_all <- (!df_dat$cdc_cov_pos)                               #            uninfected
  
  # Checking 3 groups are mutually disjoint
  if (nrow(df_dat) != sum(df_dat$symp_all + df_dat$asymp_all + df_dat$uninf_all)) {
    stop("Not mutually disjoint (!)")
  }
  
  # Date of symptom onset
  df_dat$d_s_all                   <- df_dat$cdc_symptom_startdt
  df_dat$d_s_all[df_dat$symp_all]         #  symptomatic infected
  df_dat$d_s_all[df_dat$asymp_all] <- Inf # asymptomatic infected
  df_dat$d_s_all[df_dat$uninf_all] <- Inf #            uninfected
  
  # Checking no missing dates of symptom onset for those symptomatic infected
  if (sum(is.na(df_dat$d_s_all[df_dat$symp_all])) != 0) {
    stop("Dates of symptom onset for those symptomatic infected are missing (!)")
  }
  
  ## Right bounds for date of infection ##########################################
  
  # Find index cases
  df_dat$cdc_cov_primary <- (df_dat$cdc_cov_primary == 1)
  
  # Right bounds for date of infection
  # using the dates of symptom onset
  df_dat$d_iR_all                         <- Inf
  df_dat$d_iR_all[df_dat$symp_all]        <- df_dat$d_s_all[df_dat$symp_all]                   # cannot be infected after day of onset
  df_dat$d_iR_all[df_dat$cdc_cov_primary] <- pmin(df_dat$d_iR_all[df_dat$cdc_cov_primary], 0)  # since date where index swabbed positive taken as time zero
  
  # Right bounds for date of infection
  # using the dates of positive test
  df_dat$d_iR_all[df_dat$cdc_cov_pos] <- pmin(df_dat$d_iR_all[df_dat$cdc_cov_pos], df_dat$cdc_cov_firstanyposdt[df_dat$cdc_cov_pos])  # must have been infected before positive test
  
  # Convert the numeric vector to a difftime vector in days
  df_dat$d_iR_all <- as.difftime(df_dat$d_iR_all, units = "days")
  
  # Checking if all date of infection is earlier than date of symptom onset
  if (sum(df_dat$d_iR_all > df_dat$d_s_all) != 0) {
    stop("Dates of infection are after dates of symptom onset (!)")
  }
  
  ## Order within each household #################################################
  
  # Order data in each household by symptom onset date, also putting asymptomatic hosts before uninfected hosts
  df_dat$id_old <- 1:nrow(df_dat)                                           # individual id (old)
  df_dat$id_new <- order(df_dat$cdc_hhid, df_dat$uninf_all, df_dat$d_s_all) # individual id (new)
  df_dat        <- df_dat[df_dat$id_new, ]
  
  ## Excluding households ########################################################
  
  # Assumed maximum possible gap between successive symptom onset dates within a household
  max_onsetdiff <- 28
  
  # Separate out clusters when the maximum onset difference is exceeded
  no_households_incl            <- 0
  households_incl_old           <- c()
  households_incl_new           <- c()
  household_no_new_incl         <- c()
  household_sizes_old_incl      <- c()  # counting thrown out hosts of unknown status
  household_sizes_new_incl      <- c()  # not counting thrown out hosts
  household_size_indiv_old_incl <- c()
  household_size_indiv_new_incl <- c()
  household_months_incl         <- c()
  d_s_incl                      <- c()
  d_iR_incl                     <- c()
  symp_incl                     <- c()
  asymp_incl                    <- c()
  uninf_incl                    <- c()
  onset_diffs_incl              <- c()
  
  for (household in unique(df_dat$cdc_hhid)) {
    # Extract indices, symptom onset dates, and status of all individuals in household
    household_inds  <- which(df_dat$cdc_hhid == household)         # individual id
    household_d_s   <- df_dat$d_s_all[household_inds]              # days from index case being swabbed to the date if illness (cases and contacts)
    household_d_iR  <- df_dat$d_iR_all[household_inds]             # right bounds for infection date of each host
    household_symp  <- df_dat$symp_all[household_inds]             # symptomatic
    household_asymp <- df_dat$asymp_all[household_inds]            # asymptomatic
    household_uninf <- df_dat$uninf_all[household_inds]            # uninfected
    
    # Household size, number who developed symptoms, month in which index case was recruited
    no_in_household_old  <- df_dat$hh_number[household_inds[1]]  # counting thrown out hosts of unknown status
    no_in_household      <- length(household_inds)               # not counting thrown out hosts
    no_symp_in_household <- sum(household_symp)
    
    # Only keep the data from the household if
    # (i) it contains more than one household member of known infection status, and
    # (ii) each gap between successive symptom onset dates is no larger than the permitted maximum
    household_onset_diffs    <- diff(household_d_s[household_symp])
    household_onset_diff_max <- ifelse(length(household_onset_diffs) == 0, NA, max(household_onset_diffs))
    
    if ((no_in_household > 1) && (is.na(household_onset_diff_max) || household_onset_diff_max <= max_onsetdiff)) {
      # numeric vector
      no_households_incl            <- no_households_incl + 1                                                        # number of households
      households_incl_old           <- c(households_incl_old, household)                                             # household id (old)
      households_incl_new           <- c(households_incl_new, no_households_incl)                                    # household id (new)
      household_no_new_incl         <- c(household_no_new_incl, rep(no_households_incl, no_in_household))            # household id (new)
      household_sizes_old_incl      <- c(household_sizes_old_incl, no_in_household_old)                              # number in household (old)
      household_sizes_new_incl      <- c(household_sizes_new_incl, no_in_household)                                  # number in household (new)
      household_size_indiv_old_incl <- c(household_size_indiv_old_incl, rep(no_in_household_old, no_in_household))   # number in household (old)
      household_size_indiv_new_incl <- c(household_size_indiv_new_incl, rep(no_in_household, no_in_household))       # number in household (new)
      # logical vectors
      d_s_incl                      <- c(d_s_incl, household_d_s)                                                    # days from index case being swabbed to the date if illness (cases and contacts)
      d_iR_incl                     <- c(d_iR_incl, household_d_iR)                                                  # right bounds for infection date of each host
      symp_incl                     <- c(symp_incl, household_symp)                                                  # symptomatic
      asymp_incl                    <- c(asymp_incl, household_asymp)                                                # asymptomatic
      uninf_incl                    <- c(uninf_incl, household_uninf)                                                # uninfected
    } else {
      print(household_inds) # discarded individual id
    }
  }
  
  # Data of each individual
  df_data_individual <- data.frame(
    # numeric vector
    household_no_new_incl,
    household_size_indiv_old_incl,
    household_size_indiv_new_incl,
    # logical vectors
    d_s_incl,
    d_iR_incl,
    symp_incl,
    asymp_incl,
    uninf_incl
  ) %>%
    # specific household sizes
    filter(case_when(
      hh_size == "2" ~ household_size_indiv_new_incl == "2",
      hh_size == "3" ~ household_size_indiv_new_incl == "3",
      hh_size == "4" ~ household_size_indiv_new_incl == "4",
      hh_size == "5p" ~ as.integer(household_size_indiv_new_incl) >= 5,
      hh_size == "2or3" ~ household_size_indiv_new_incl %in% c("2", "3"),
      hh_size == "4p" ~ as.integer(household_size_indiv_new_incl) >= 4,
      TRUE ~ TRUE  # Keep all rows when hh_size does not match any of the above conditions
    )) %>%
    mutate(household_no_new_incl = dense_rank(household_no_new_incl))
  
  # Data of each household
  df_data_household <- data.frame(
    household_sizes_old_incl,
    household_sizes_new_incl
  ) %>%
    # specific household sizes
    filter(case_when(
      hh_size == "2" ~ household_sizes_new_incl == "2",
      hh_size == "3" ~ household_sizes_new_incl == "3",
      hh_size == "4" ~ household_sizes_new_incl == "4",
      hh_size == "5p" ~ as.integer(household_sizes_new_incl) >= 5,
      hh_size == "2or3" ~ household_sizes_new_incl %in% c("2", "3"),
      hh_size == "4p" ~ as.integer(household_sizes_new_incl) >= 4,
      TRUE ~ TRUE  # Keep all rows when hh_size does not match any of the above conditions
    ))
  
  # Save data
  save(df_data_individual,
       df_data_household,
       household_months_incl,
       file = paste0("../R/Results-temp/", scn, "/RData/data_initial.RData"))
}
